markdown: redcarpet
highlighter: null
permalink: /:categories/:year/:month/:day/:title 

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed