markdown: redcarpet
highlighter: null
permalink: /:categories/:year/:month/:day/:title 

url:
baseurl: http://tegabyte.com

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
  
comments :
    provider : duoshuo
    duoshuo : 
      short_name : tegabyte